
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Submodule Sync
        uses: mheap/submodule-sync-action@v1
        with:
          # The path in the repo to update
          path: MaterialSkin
          # The branch name to check for updates in the remote repo
          ref: master
          # The name of the branch to use when creating a pull request
          pr_branch: master        
